### ISSUE TITLE
Folder View Font Size Graphics

### ISSUE THREAD

**Issue by Zvan2000** [nousacademy/jMarks#6]
Font Size to be 11 Pixels
Use Folder icon from Xmarks
![folder-closed](https://cloud.githubusercontent.com/assets/14854320/10120527/01395958-648c-11e5-81ee-92ea6fba9b36.gif)

**Comment by nousacademy** [comment]
![folder](https://cloud.githubusercontent.com/assets/7450944/11319719/65739a80-904e-11e5-8ec2-b5b02209a154.png)

**Comment by nousacademy** [comment]
![screen shot 2015-11-22 at 10 29 03 am](https://cloud.githubusercontent.com/assets/7450944/11324595/f3511df4-9103-11e5-981e-b6ee9b39886d.png)
