### ISSUE TITLE
Not sure what I need this extension for?????

### ISSUE THREAD

**Issue by Zvan2000** [nousacademy/jMarks#7]
I need to re evaluate how i want to organize my life

**Comment by nousacademy** [comment]
To replace xmarks wasn't that the original purpose? Because xmarks doesn't allow you to store images and move them around.

**Comment by nousacademy** [comment]
Anything that xmarks has can be replicated. And we can add Pinterest to jMarks and that would function as your shareable folder

**Comment by nousacademy** [comment]
Use case scenario: You can " pin " anything on any site that has the Pinterest button and it will immediately show up on jMarks

**Comment by nousacademy** [comment]
TODO:

I don't know what I want anymore.  My affirmations:
Ill always have bookmarks. 
Ill always have contacts.
Ill always download things from the internet; Bookmarks, web pages, Images, Text, Videos, Gifs.
Ill always have email.
Ill always text.
Ill want to share some of these but not all.
Ill always be cross platform (it hurts to say this but its really a function of cross device PC, Imac, Ipad, Iphone, Smart TV, Smart Wearables, etc.)
I will always want to sort and link these things in the simplest way.  Its almost like I want viewports into the different parts of my life with the ability to sort and re-present this information.  While hierarchy works in a file structure the real organization comes from re-presenting the information in different ways.  Viewports into my Matrix.

Again here are some interesting websites that is use:

Xmarks (of course)  This is the starting point but the list below is vast
GQues
Amazon
Ebay
Youtube
Yahoo 
Google Drive
Pinterest
Soundcloud
Houzz
Evernote
One Note
Zoho Docs
gimme bar
Fark
Reddit
Pandora
Eater
Google Earth
Netflix
Picasa
Flickr
Morpholio, trace, board, etc.
All my news feeds
All my banking

**Comment by nousacademy** [comment]
You can integrate Google Maps, thats pretty easy, as long as they have an API I can plug them in.

**Comment by nousacademy** [comment]
On each item of the list, you need to be more specific @Zvan2000 . This will be the mother ship!

**Comment by nousacademy** [comment]
Banks don't expose their APIs by the way.

**Comment by nousacademy** [comment]
if they do might have to pay for it..
