### ISSUE TITLE
Portability and Access

### ISSUE THREAD

**Issue by Zvan2000** [nousacademy/jMarks#8]
This extension needs to be used on all devices and synced between them.

I think that means it needs to be a website also? This would give me the ability to access my Jmarks from other peoples devices without the extension installed.  the extension needs to be installable from online not a flashdrive.  This is how X-Marks works

**Comment by nousacademy** [comment]
@Zvan2000 Just make it an app but remember there won't be any right click functionality on mobile devices. I was also thinking that we should  make this a private github repo (no one will have access besides us) and whenever I update this you just download the zip and install it on your comp

**Comment by nousacademy** [comment]
You don't need a website, go the app route

**Comment by nousacademy** [comment]
But you have to tell me specifically what you want to be ported on it and I have to find out if they made their API's available for consumption.
